name=SparkFun u-blox GNSS v4
version=4.1.0
author=SparkFun Electronics <techsupport@sparkfun.com>
maintainer=SparkFun Electronics <sparkfun.com>
sentence=Library for I2C, Serial and SPI Communication with u-blox GNSS modules<br/><br/>
paragraph=An Arduino Library to support the latest u-blox GNSS modules, using both NMEA and UBX protocols over I2C, Serial and SPI.<br/><br/>Useful for interfacing to the <a href="https://www.sparkfun.com/sparkfun-allband-gnss-rtk-breakout-zed-x20p-qwiic.html">SparkFun Allband GNSS RTK Breakout - ZED-X20P (GPS-28871)</a>.<br/>
category=Sensors
url=https://github.com/sparkfun/SparkFun_u-blox_GNSS_v4
architectures=*
